import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { notoSans, ubuntu } from '../app/fonts';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${ubuntu.variable} ${notoSans.variable} font-notoSans text-black-text bg-white-bg`}
      >
        <Component {...pageProps} />
      </div>
    </>
  );
}
